[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0"

# The title and description fields are primarily for displaying extension info in UI
title = "Convai Character API"
description="Integrate Convai API with Omniverse."

icon = "data/icon.png"
preview_image = "data/preview.png"


# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

feature = true

# URL of the extension source repository.
repository = "https://github.com/Conv-AI/ov_extension"

# One of categories for UI.
category = "Convai"

# Keywords for the extension
keywords = ["kit", "convai", "chatgpt", "chatbot"]


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}
"omni.anim.graph.bundle" = {}

# Main python module this extension provides, it will be publicly available as "import convai".
[[python.module]]
name = "convai"
