[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# The title and description fields are primarily for displaying extension info in UI
title = "Convai Chatbot"
description="Integrate Convai chatbot API with Omniverse, please check README file."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = "https://github.com/Conv-AI/ov_extension"

# One of categories for UI.
category = "Convai"

# Keywords for the extension
keywords = ["kit", "convai"]


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main python module this extension provides, it will be publicly available as "import convai".
[[python.module]]
name = "convai"
